### ISSUE TITLE
platforms/avr/led_sysdefs_avr.h: No such file or directory

### ISSUE THREAD

**Issue by stevesparks** [focalintent/FastLED-Sparkcore#2]
Veryfing code using this library in Particle Build fails with this error:
```
FastLED/led_sysdefs.h:19:43: fatal error: platforms/avr/led_sysdefs_avr.h: No such file or directory
 #include "platforms/avr/led_sysdefs_avr.h"
                                           ^
```

My code is cribbed from the "Fire2012" example.

**Comment by enjrolas** [comment]
I'm seeing the same error when building any of the fastLED examples for Photon.  They run fine on a spark core, but I can't build anything for a photon.  I forked the library and am working on a fix now -- I'll comment if I get anywhere.

**Comment by stevesparks** [comment]
@enjrolas I have also heard that it's a kernel thing and that the more recent versions of the `develop` branch in https://github.com/spark/firmware provide this functionality. I have tried running that kernel and bricked one of my Photons. :/

**Comment by focalintent** [comment]
FastLED doesn't fully support the photon yet, which is most likely the biggest source of issues for folks trying to build for it.

**Comment by webdevbrian** [comment]
Dan! Again, we meet again! Let me (and others I'm sure) know if you have a paypal donation link -- your library is a huge part of our livelihood for sure. I think I speak for others with this, and obviously myself but thank you for such the hardwork on this lib. It is HUGELY appreciated.

**Comment by wmoecke** [comment]
This seems to be caused by FastLED library not loading the correct header file for the Photon platform. It's somehow defaulting to AVR - I've confirmed my suspicion after doing a Google search and finding [this thread] (https://community.particle.io/t/fastled-on-photon/11933/3).
It also seems that the developers are aware of this issue for quite some time, and they've already got a hold of some photons so I am convinced it's only a matter of time until we can use FastLED on the photons.

Btw, thanks a lot to the developers for this amazing library.

**Comment by focalintent** [comment]
Yes - because there are so many arduino variants and because of some fallback things I have in the code if the library doesn't recognize the platform you are building for it drops back to unspecified arduino based avr.

**Comment by stevesparks** [comment]
In my surfing, I also encountered some discussion of a [branch of the Particle firmware](https://github.com/spark/firmware/tree/develop) that claims to add the necessary features for one to compile locally. I downloaded this firmware, built it, flashed it. It was not retaining wifi credentials between  power cycles. 

I didn't achieve anything valuable, quite the opposite: about 20 minutes into playing with it, I accidentally touched 5V to the 3V3 pin and cooked it. :-1:

**Comment by webdevbrian** [comment]
Thank you Dan - for all of your hardwork!!!

**Comment by wmoecke** [comment]
@stevesparks, you've brought up an interesting subject. I've currently got 2 photons, the first one I had worked for a few days, and after flashing a series of sketches built using the particle IDE, one day it decided by itself to never forget its wifi settings (not even after a full factory reset performed several times), and flashes from the particle IDE, but you never see anything going on. 

This one I had purchased from @enjrolas for his L3D cube. He sent me a replacement, which last evening after the confusing setup (never can get it to work right the first time without debugging) I got connected and had flashed it a few times with the same sketch to make sure it was working OK.
But then, I powered it down for an hour or so, and when I powered it back on it had not only forgotten the wifi settings (just like yours apparently) but also the firmware I had loaded last into it.

So I might be asking a dumb question, but is there a way to flash firmware into the photon (just like you would do a bootloader flash via ICSP into the Arduino's Mega328P) - and *really* reset everything on the hardware, or are we stuck with the known options (cloud, USB flash)?

**Comment by wmoecke** [comment]
ummm, regarding my last question, it seems the option would be to put the device in DFU mode and use the CLI utilities to load the compiled binary - as it is explained in item #4 on the README.md.
I was hoping to try and revive my 'dead' photon but I recall having tried to flash it with the device in dfu mode but it yielded nothing.

**Comment by stevesparks** [comment]
@wmoecke Great questions and I want the answers too; Let's go find an answer, but probably not in the FastLED repo. :grinning:

**Comment by wmoecke** [comment]
Makes perfect sense, I apologize for the off-topic. Got carried away.  :-)


 "Success consists of going from failure to failure without loss of
enthusiasm" - Winston Churchill


2015-07-18 19:38 GMT-03:00 Steve Sparks <notifications@github.com>:

**Comment by stevesparks** [comment]
@wmoecke If the code commits I referenced find their way into the device firmware updater supported by https://build.particle.io/build, I would expect the stock build of FastLED to just start working and moot this issue entirely.

I suggest that @focalintent need not work on this immediately, but instead, we might wish to push for Particle to make the change.

**Comment by wmoecke** [comment]
But @stevesparks, how about that issue you mentioned when you flashed that fork into your photon? Wouldn't that affect all photons that try to use the library flashing code from the particle IDE?

**Comment by stevesparks** [comment]
The underlying truth here is that Particle shipped us Photon parts containing a given build, "Build X". Their UI offers a FastLED library for Photon development which is not compatible with Build X. I'm sure this is a mixup because I assume FastLED works fine on Core. Solution: Particle needs to fix FastLED in their UI for Photon, or strip it out.

If this involves pushing new Photon firmware that works as well as the current shipping stuff and includes those `#define` statements, fine with me. If it involves them hacking their copy of FastLED, pretty much also fine with me. Either way I feel like it's their bug to fix.

**Comment by focalintent** [comment]
No, it is my bug to fix - because every hardware platform requires extensive plowed/validation/optimization.  Personally I wouldn't trust particle to port FastLED to their platform (and from a quick look at the data sheets the I/o register layout for the photon is different enough from what's used in the core that it isn't going to just be a couple of quick defines to make it work.

**Comment by focalintent** [comment]
To expand on my above comment, FastLED is unique amongst most arduino-style/friendly libraries in that I bypass pretty much everything in the arduino environment and talk directly to the underlying hardware at the lowest levels (sometimes in asm, even bypassing the compiler).  It means that porting FastLED to new hardware often involves an evening (or few) digging through the data sheet/user manual for the cpu (and really, how many arduino users are even aware that there is dedicated documentation at such a low level).

**Comment by wmoecke** [comment]
Ummm, that explains the 'fast' in FastLED - It's been literally just a few days since I've been made aware of this library, and since my first glimpse at some of the high level code, been thinking, "how the hell they've managed to make the calculations so much faster on the arduino" - now there's the answer.  :+1: 

Coding in pure assembly language comes with a price - it's not 'adaptable' or 'portable' in any sense. Each new hardware platform will require its own version coded to cope with their idiossincrasies. I hope I spelled that word right. Too late for googling now.

**Comment by rschanafelt** [comment]
So is this still an open issue? Will using this with a Particle Photon brick the device?

**Comment by focalintent** [comment]
Yes, this is still an open issue, I haven’t had the time to work on the Photon port yet.

**Comment by rschanafelt** [comment]
@focalintent I'm hoping to get an installation up and running for Halloween using the Particle Photon / FastLED / DotStars. Is there anything I can do to help? (Unfortunately my ASM skills are way out-of-date or I'd take a crack at porting it myself.) I'm curious about when you might take this on, or how the community could help? As with all open source projects, I'm grateful for your efforts to port this, so a big thanks for your work!

**Comment by focalintent** [comment]
Mostly it is just a matter of getting the time to work on it - I have a full time job and a couple of contracting jobs that are taking up my time at the moment.  If things go well, I can probably poke at it a bit next weekend.

**Comment by causticforms** [comment]
Got here through a search for the aforementioned error. I'd love to see a port happen at some point. :)

**Comment by MrRocketman** [comment]
One more vote for a port! I got as far as figuring out that to detect the photon I need:

#elif defined (STM32F2XX)

Then I ran into about a thousand errors because I undoubtedly have my project setup wrong. I would be happy to donate as well if it helps. I really need this library for my Halloween/Christmas lights! The NeoPixel library is nowhere near fast enough!

Thanks!
James

**Comment by eklex** [comment]
Good news, everyone! I added the support for Photon.
See my [comment](https://github.com/FastLED/FastLED/issues/166#issuecomment-150089348) in the master FastLED library.

**Comment by ScruffR** [comment]
Would be nice if the corrected version could be pushed to Particle Build (Web IDE) soon.

**Comment by focalintent** [comment]
I've pulled the pull request over to the branch - does the particle build ide not pick it up?  (I really hate their dev environment sometimes).

**Comment by ScruffR** [comment]
Unfortunately not. 
You'd have to nodge up the version number in `spark.json` (which I think you did already anyway) and the go into Particle Build, into libraries (as you did first time putting it online) and <kbd>CONTRIBUTE LIBRARY</kbd> again.
After validating and importing the new version you need to publish it again too.

All that to ensure that no half-baked commits or untested work-in-process versions go public.

**Comment by focalintent** [comment]
Heh - I haven't touched the particle build ide since putting up the initial version of the library - I'll hopefully have some time to poke at it over the thanksgiving break.

**Comment by ScruffR** [comment]
That would be great :+1:

**Comment by blownupp** [comment]
I'm sorry if I am missing something obvious here, but has this been pushed through yet? I just tried building "Fire2012.ino" on my Photon running the latest firmeware and latest FastLED and I'm getting that same AVR #include issue.

focalintent - I appreciate the work you've put into this, thank you.

Everyone else - thanks for your time!

**Comment by RickDB** [comment]
Is the fixed library already in the particle build environment or do I need to manually add it via the local IDE?
As the current version there is 3.1.3 but still get the same error from the op.

**Comment by focalintent** [comment]
I need to actually push the changes to the web based build system - which i'll do when I get back from traveling for the holidays.

**Comment by RickDB** [comment]
Awesome, thanks :+1:

**Comment by lessavyfav** [comment]
So excited for Fast LED! Thanks, refreshing the IDE like a kid at Christmas. I'm no whiz but if there is anything I can do to help please let me know. 

I've not been able to get code to work using the local Particle IDE - it compiles successfully but then, after flashing ,my Photon goes into S.O.S. mode with 5 blinks for "Usage Fault" which I don't get...

**Comment by Jarmom** [comment]
Rather excited to get FastLED onto my Photon as well! Been waiting a while for this! Hope your holidays went well, Dan!

**Comment by focalintent** [comment]
Pushed to the particle ide - thanks again, @eklex for doing the kicks!

**Comment by enjrolas** [comment]
I'm still getting a build error in the particle web IDE -- the usual
FastLED/led_sysdefs.h:19:43: fatal error: platforms/avr/led_sysdefs_avr.h: No such file or directory
 #include "platforms/avr/led_sysdefs_avr.h"
                                           ^
@focalintent  -- is it working for you in the particle web IDE, or the local IDE?

**Comment by enjrolas** [comment]
FWIW, I also downloaded the current git repo, added the project folder to the local particle dev IDE, and tried to compile, and I got the same error.

**Comment by focalintent** [comment]
I currently do not have a setup that I can easily test sparkcore stuff with (and won't for another week or so - juggling a bunch of other stuff and need to find my particle hardware) - so I'm relying on @eklex's work for the moment.  However, multiple people have reported being able to pull the current https://github.com/focalintent/FastLED-Sparkcore master and have it work for them - so I wonder if there's something else going on with your setup? 

Although it's looking like something in the particle web ide didn't update.  

(I really hate their web ide/platform from a library maintainer standpoint, it's almost irritating enough to the point where I sometimes get tempted to completely punt spark core/photon support - as it is, the spark core library is always behind what I do on the main FastLED repo)

**Comment by focalintent** [comment]
It looks like there's something you have to do in the particle IDE to use a newer version of a library, it's not enough for me to update the library version.

**Comment by RickDB** [comment]
Yeah had the same issue and selecting 3.1.4 manually fixed it.
Did have to change some things from the FastLED sample sketch as otherwise it wouldn't compile, got it to work in my AtmoOrb sketch like this:

https://github.com/ambilight-4-mediaportal/AtmoOrb/blob/master/Particle/Photon/AtmoOrb_UDP.ino

**Comment by focalintent** [comment]
Yeah - not all of the sample sketches have the ```FASTLED_USING_NAMESPACE;``` bs in there - where there other changes you had to make?

I'l try to keep the library more up to date - there's a bunch of major changes coming down the line (check out https://github.com/FastLED/FastLED/wiki/RGBSet-Reference) - but the fact that the sparkcore stuff has to live in a separate repo makes keeping it in sync a pain in the ass :(

**Comment by RickDB** [comment]
Sample had #include "FastLED.h" in there but particle IDE places the correct one with extra path at the top automatically so that fixed itself, also added the version check from the library at the top just in case.
CRGBSet looks very nice, thanks for your on this as this is so much better than NeoPixel :+1:

**Comment by ScruffR** [comment]
One or two things you need to do/know about libraries in Particle Build is that it keeps a local "inventory" of known libraries that might need to be refreshed to make a new version visible (sometimes you even need to press the `CLEAR CACHE` button in the Build properties drawer).
And once you import a lib to your project its files will actually be copied over into your remote project folder (which you never actually see), so whatever updates happen on the original library will not be carried over to your project to avoid possible breaking of running code.
To upgrade an already imported lib, you need to remove the old one and reimport the new one.

**Comment by Jarmom** [comment]
I just wanted to take a minute to thank you, Dan. I really appreciate all the hard work you put into keeping things up to date! I'll definitely be playing with the library for some time to come! Keep up the awesome work! :+1:

**Comment by tchinou1** [comment]
I cleared the cache and I created a new app, but I still get this error. Am I doing anything wrong ?
FastLED/led_sysdefs.h:19:43: fatal error: platforms/avr/led_sysdefs_avr.h: No such file or directory
 #include "platforms/avr/led_sysdefs_avr.h"

Thanks Dan for the library, I'm using it on arduino and I really love it !

**Comment by focalintent** [comment]
You have to go into the info for the library and make sure you are using version 3.1.4 or later of the library.  As mentioned, particle's build system doesn't seem to do this automatically.  Unfortunately I can't describe exact steps to you right now because their web ui isn't loading for me at all.

**Comment by RickDB** [comment]
@tchinou1 

Add some step by step screenshots:

Step 1 - Select Library as normal

http://s15.postimg.org/aqb98kt57/step1.png

Step 2 - Click on the highlighted info button

http://postimg.org/image/8x8ck97yf/

Step 3 - Click on the highlighted 3.1.4 version

http://postimg.org/image/eb74rsxon/

Step 4 - 3.1.4 should now be selected where after you can add it your app

http://postimg.org/image/s11o0lksn/

**Comment by tchinou1** [comment]
Thanks yes I don't get the error anymore, but I get a bunch of weird errors. Like if the library wasn't include, but it is.
Ex: 
error: 'CRGB' does not name a type
error: 'TProgmemRGBPalette16' does not name a type
error: 'FastLED' was not declared in this scope

**Comment by RickDB** [comment]
Make sure to use this at the top as some of the samples out there are invalid.

```
#include "FastLED/FastLED.h"
FASTLED_USING_NAMESPACE;

#if FASTLED_VERSION < 3001000
#error "Requires FastLED 3.1 or later; check github for latest code."
#endif
```

Full example here using that here:

https://github.com/ambilight-4-mediaportal/AtmoOrb/blob/master/Particle/Photon/AtmoOrb_UDP.ino

**Comment by tchinou1** [comment]
Thanks it's working right now ! :)

**Comment by lessavyfav** [comment]
As always, thanks to Dan and all for the huge efforts they make. Please post a paypal donate address! I am so happy the you've ported to photon but am struggling with lots of noise and chatter/flickering on larger chains of APA102c. 1m of 30 per works well, one I get to 2 m things fall apart. I hope to get an 11/66 matrix running for these kids I'm volunteering with so the situation has me sweating. 

Using the dotstar library works a lot better... Spidiey senses tingle around data rate, maybe the speed is less forgiving over greater lengths? But get an error with this declaration while plugged to default(?) A5 data and A3 clock


FastLED.addLeds<APA102, RGB, DATA_RATE_MHZ(12)>(leds, NUM_LEDS);

It doesn't like  I looked a bit into dividing SPI rate in Photon reference materials but am out of my league with clock level stuff. Do I need to run SPI begin? Set its frequency? . Maybe someone have advise on pin setting/best timing with photon and APA102s.

I'm converting to 5v levels for data with a 74hct245. I'm going to try distorting powers more frequently first but ask about the clock assuming I'll be back soon ;-)

Thanks for reading This prattling comment. Sorry.

**Comment by focalintent** [comment]
https://github.com/FastLED/FastLED/wiki/SPI-Hardware-or-Bit-banging documents how to adjust the SPI data rate.  The dotstar library defaults to an 18Mhz data rate, slower if you are bit-bnaging (e.g. using non-hardware SPI pins) - FastLED defaults to 24Mhz, and I've seen that be a problem with longer strips.  FastLED is pretty aggressive in the bit-banging code, it's possible it is running too quickly (I can toggle clock lines _really fast- very easily :) - changing the data rate down to something like 10-12Mhz might help with what you're seeing.

(Also - in the future - more conversational help type stuff should go to the g+ community - http://fastled.io/+ - or into new issues - having an issue veer off into a half dozen different things makes them far less useful in the long run :)

**Comment by focalintent** [comment]
Ah!  Now I remember - I haven't actually implemented hardware SPI support for the photon/spark core (their web ui/dev environment got to be too irritating for me to keep working on it) - so everything is going to use bit-banging - which, if the data rate is set to high may result in flipping ports too quickly.  (As it is, I think there's a performance optimization in there that I have to take out because it causes too many problems - but in the meantime, changing the data rate to something lower should help).

**Comment by blownupp** [comment]
Just to add to what lessavyfav was saying I am having the same issue - 1m
144led apa102 string glitching out quite a bit. I'll have to give the data
rate a shot though. How difficult would it be for one to add support for
hardware SPI? I'm not expert programmer but if it isn't anything too
difficult I wouldn't mind poking around...

**Comment by Hotaman** [comment]
@focalintent 1+ on the pita web IDE (I maintain the Particle (Spark) OneWire lib) and Thanks for your work on this one. I have been playing with 1m x 60 DotStars using my own code and hardware SPI on the Photon and Electron. I'm driving the interface directly (3.3v I'd only switch to 5v if I had long wires between the Photon and the strip, bout 12" now) to the DotStars and running the data at 50MHz without issue. The OneWire lib is all bit banged and when doing high speed banging on bits you need to take some special care depending on the specific platform if using fast pin functions (I haven't looked yet but I will be). I have a 4mx60 strip on the way that I will test with this coming weekend. I'll post the results using hardware SPI and your bit banging if I can get the lib to compile and run.

Since I'm only planning to use the APA102 LEDs, I vote for hardware SPI support, forget the bit banging!

This repo was last updated 2 months ago, I pulled it a couple days ago for local dev and had the AVR error. In the webIDE, switching to 3.1.4 passes that error which makes me wonder 'where is the latest code for Particle?'

I'm sure I'll figure it out, once I get a test running I'll test on the Electron as well for you.

**Comment by kri5** [comment]
:+1:

**Comment by kri5** [comment]
@Hotaman You might want to open an new issue and ping @focalintent

**Comment by Hotaman** [comment]
@kri5 
I have it compiling now in dev with the Fire2012 demo on a Photon. I just needed to track down all the required defines and values. The json indicates it is the correct code and it does work just fine when properly configured.

Probably the biggest problem is that none of the examples currently work out of the box so there is no base reference as to how to get it to work. You have to want it!

**Comment by RickDB** [comment]
For a working sample of Fire2012 with programmable Color Palette with FastLED and Photon you could go with this one:

https://gist.github.com/RickDB/aec4cdc3a84310f81f05

**Comment by wmoecke** [comment]
> Make sure to use this at the top as some of the samples out there are invalid.
> 
> ```
> #include "FastLED/FastLED.h"
> FASTLED_USING_NAMESPACE;
> 
> #if FASTLED_VERSION < 3001000
> #error "Requires FastLED 3.1 or later; check github for latest code."
> #endif
> ```

Hooray! Adding `FASTLED_USING_NAMESPACE;` is exactly what I needed to do in order to fix my FastLED code written on a local build environment (using the CLI tools to compile on the cloud).
It fixed the `fatal error: platforms/avr/led_sysdefs_avr.h: No such file or directory` error I was getting with the ColorPalette.ino example (this particular one didn't have that statement) - was driving me crazy!

Thank you, thank you, thank you @RickDB for the fix, @focalintent for this lib. I'm stoked. I modified the NoisePlusPalette.ino code to spread the visuals across a 8x8x8 LED cube made out of 512 WS2812B's.

Happy.
